### PR TITLE
bringing up to current sqlalchemy module layout

### PR DESCRIPTION
**Pull request by rblomberg**
This should be safe... should probably verify when the exceptions to exc module name change happened and add an install_requires into setup.py.  I added a few changes to setup.. will send those next

### CODE REVIEW

**Comment by mjpizz** [comment]
thanks, just ran this locally and it seems to be okay. You mentioned sending some other changes to setup.py next - did you already do those in https://github.com/mjpizz/stockpyle/pull/1/commits/313992723e064b2648105a6c42a14311e9249dde?

**Comment by rblomberg** [comment]
Yep

**Comment by mjpizz** [comment]
Released as version 0.1.8 - thanks Ryan!

**Comment by rblomberg** [comment]
no problem at all

**Pull request merged**
